POST http://localhost:8080/acolhe/clinicas/adicionar
Content-Type: application/json

{
  "nmClinica": "tee a3ddkfjkghssa",
  "email": "api@alse.asjjcom",
  "telefone": "123678712j2890",
  "descricao": "hahahjahaah",
  "imagem": "URL da Imagem",
  "bairro": "Bairro",
  "cidade": "Cidade",
  "nmEstado": "Nome do Estado",
  "sgEstado": "sp",
  "patrocinada": true,
  "nivelSatisfacao": 4
}
